name: Create Release

on:
  push:
    branches:
      - dev

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install
        working-directory: ./

      - name: Run Semantic Release Action
        uses: ./ # Use local action for testing; replace with your action's repository path when publishing.
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}